config/routes.rb
Rails.application.routes.draw do
  get 'manage_answer/edit'

  get 'manage_answer/index'

  get 'manage__questions/new'

  get 'manage__questions/edit'

match 'manage__questions_ajax/edit' => 'manage__questions_ajax#edit', via: :get
match 'manage_answer/index' => 'manage_answer#create', via: :post
match 'manage_answer/edit' => 'manage_answer#update', via: :put
  get 'edit_poll_questions_ajax/index'

  get 'add_questions_ajax/index'
  match 'add_questions_ajax/index' => 'add_questions_ajax#create', via: :post
  match 'edit_poll_questions_ajax/index' => 'edit_poll_questions_ajax#update', via: :put
  resources :add_questions
  get 'make_form/index'
  match '/make_form/index' => 'make_form#add_reference', via: :post
  resources :polls
  resources :answers
  resources :questions
  get 'show_poll/index'
  root 'polls#index', as: 'polls_index', via: :all

 

 

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/questions_controller.rb
  class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.where("polls_id=?",params[:poll_id])
    #@questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @questions = Question.where("polls_id=?",params[:poll_id])
    @answers=Answer.where("questions_id =?",@question.id)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to manage_answer_index_path(question_id: @question), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to manage_answer_edit_path(question_id: @question), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:description)
    end

    def createAjax
      @question = Question.new(question_params)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
    <tr>
    	<td></td>
    	<td><%= question_counter+=1 %></td>
        <td><%= question.description %></td>
     </tr>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>
<% @questions=Question.all %>
<% counter=0 %>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
      	<td></td>
      	<td><%= counter+=1 %></td>
        <td><%= question.description %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>
	<div id="4b" style="padding-left: 5px; padding-right: 5px; padding-top: 5px; padding-bottom: 5px; margin-left:4em">
		<strong>Answers:</strong>
		<ul>
			<% @answers.each do |answer|  %>
			<li>
				<%= answer.description %>
			</li>
			<% end %>
		</ul>
	</div>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>