config/routes.rb
Rails.application.routes.draw do
  get 'manage_answer/edit'

  get 'manage_answer/index'

  get 'manage__questions/new'

  get 'manage__questions/edit'

match 'manage__questions_ajax/edit' => 'manage__questions_ajax#edit', via: :get
match 'manage_answer/index' => 'manage_answer#create', via: :post
match 'manage_answer/edit' => 'manage_answer#update', via: :put
  get 'edit_poll_questions_ajax/index'

  get 'add_questions_ajax/index'
  match 'add_questions_ajax/index' => 'add_questions_ajax#create', via: :post
  match 'edit_poll_questions_ajax/index' => 'edit_poll_questions_ajax#update', via: :put
  resources :add_questions
  get 'make_form/index'
  match '/make_form/index' => 'make_form#add_reference', via: :post
  resources :polls
  resources :answers
  resources :questions
  get 'show_poll/index'
  root 'polls#index', as: 'polls_index', via: :all

 

 

end

app/models/add_question.rb
class AddQuestion < ActiveRecord::Base
end

app/controllers/add_questions_controller.rb
class AddQuestionsController < ApplicationController
  before_action :set_add_question, only: [:show, :edit, :update, :destroy]

  # GET /add_questions
  # GET /add_questions.json
  def index
    @poll=Poll.find(params[:poll_id])
    @add_questions = AddQuestion.all
    @questions=Question.all
    @questions_filter=Question.where("polls_id is null")
  end

  # GET /add_questions/1
  # GET /add_questions/1.json
  def show
  end

  # GET /add_questions/new
  def new
    @add_question = AddQuestion.new
  end

  # GET /add_questions/1/edit
  def edit
  end

  # POST /add_questions
  # POST /add_questions.json
  def create
      @poll=Poll.find(params[:poll_id])
      @array_id = JSON.parse(params[:data_value])
      @array_id.each do |id|
        question=Question.find(id)
        question.polls_id=@poll.id
        question.save
      end
        respond_to do |format|
        format.html { redirect_to polls_index_path, notice: 'Poll was successfully updated.' }
        #format.json { render :show, status: :ok, location: @poll }

      end
  end

  # PATCH/PUT /add_questions/1
  # PATCH/PUT /add_questions/1.json
  def update
    respond_to do |format|
      if @add_question.update(add_question_params)
        format.html { redirect_to @add_question, notice: 'Add question was successfully updated.' }
        format.json { render :show, status: :ok, location: @add_question }
      else
        format.html { render :edit }
        format.json { render json: @add_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_questions/1
  # DELETE /add_questions/1.json
  def destroy
    @add_question.destroy
    respond_to do |format|
      format.html { redirect_to add_questions_url, notice: 'Add question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_question
      @add_question = AddQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def add_question_params
      params.fetch(:add_question, {})
    end
end

app/helpers/add_questions_helper.rb
module AddQuestionsHelper
end

app/views/add_questions/_form.html.erb
<%= form_for(@add_question) do |f| %>
  <% if @add_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@add_question.errors.count, "error") %> prohibited this add_question from being saved:</h2>

      <ul>
      <% @add_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/add_questions/edit.html.erb
<h1>Editing Add Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @add_question %> |
<%= link_to 'Back', add_questions_path %>

app/views/add_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pick a question</h1>
<input type="hidden" id="poll_id" value=<%=@poll.id %> >
<table id="mytable">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions_filter.each do |question| %>
      <tr>
        <td><input type="checkbox" name = "chkboxRoute[]" value=<%=question.id%>> <%= question.description %><br></td>
      </tr>
    <% end %>
  </tbody>
</table>
<button id="save">Ingresa preguntas</button>

<br>

<script type="text/javascript">
$('#save').click(function () {
  debugger
    varId = [];
    poll_id=document.getElementById('poll_id').value;
    //poll_id.find.('poll_id').value();
    i=0;
    $('#mytable').find('tr').each(function () {
        var row = $(this);
        if (row.find('input[type="checkbox"]').is(':checked') 
            ) {
            varId[i]=row.find('input[type="checkbox"]').val()
          i++;
        }
    });
    //here the url for questions
    $.ajax({   
        url : "/add_questions",
        type : "post",
        data : { data_value: JSON.stringify(varId) , poll_id}
    });
});
</script>

app/views/add_questions/new.html.erb
<h1>New Add Question</h1>

<%= render 'form' %>

<%= link_to 'Back', add_questions_path %>

app/views/add_questions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_add_question_path(@add_question) %> |
<%= link_to 'Back', add_questions_path %>