config/routes.rb
Rails.application.routes.draw do
  get 'manage_answer/edit'

  get 'manage_answer/index'

  get 'manage__questions/new'

  get 'manage__questions/edit'

match 'manage__questions_ajax/edit' => 'manage__questions_ajax#edit', via: :get
match 'manage_answer/index' => 'manage_answer#create', via: :post
match 'manage_answer/edit' => 'manage_answer#update', via: :put
  get 'edit_poll_questions_ajax/index'

  get 'add_questions_ajax/index'
  match 'add_questions_ajax/index' => 'add_questions_ajax#create', via: :post
  match 'edit_poll_questions_ajax/index' => 'edit_poll_questions_ajax#update', via: :put
  resources :add_questions
  get 'make_form/index'
  match '/make_form/index' => 'make_form#add_reference', via: :post
  resources :polls
  resources :answers
  resources :questions
  get 'show_poll/index'
  root 'polls#index', as: 'polls_index', via: :all

 

 

end

app/models/poll.rb
class Poll < ActiveRecord::Base
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
    #after_action :testRender , only: :show
  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
    @polls.each do |poll|
      @questions = Question.where("polls_id=?",poll.id)
    end
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
     @questions=Question.where(["polls_id =?", @poll.id])
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
    @questions = Question.where("polls_id=?",@poll.id)
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)
    respond_to do |format|
      if @poll.save
        format.html { redirect_to add_questions_ajax_index_path(poll_id: @poll) }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to edit_poll_questions_ajax_index_path(poll_id: @poll) }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      #params.fetch(:poll, {})
      params.require(:poll).permit(:title , :description , :votes)
    end

    def add_question
      @poll=Poll.find(params [:poll_id])
      @question=Question.find(params [:question_id])
      @poll.question_id=@question.id
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      end
    end
    def testRender (poll)
      if !poll.nil?
        @questions = Question.where("polls_id=?",poll.id)
      end
    end

  end

app/helpers/polls_helper.rb
module PollsHelper

	def test_add
		@poll=Poll.find(params [:poll_id])
	      @question=Question.find(params [:question_id])
	      @poll.question_id=@question.id
	      if @poll.save
	        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
	        format.json { render :show, status: :ok, location: @poll }
	    end
	end
end

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
<% if @poll.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

  <ul>
    <% @poll.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<input type="hidden" id="poll_id" value=<%=@poll.id %> >
<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>
<div class="field">
  <%= f.label :votes %><br>
  <%= f.number_field :votes %>
</div>  
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>


 

app/views/polls/_poll.html.erb
 	<% @questions = Question.where("polls_id=?",poll.id) %>
 	<tr>
    	<td><%= poll_counter+=1 %></td>
        <td><b><%= poll.title %></b></td>
        <td><%= link_to 'Show', poll %></td>
    </tr>
    <tr>   
       <td><%= render(@questions) %></td>
    </tr>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Polls</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <%= render(@polls) %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Title:</strong>
	<%= @poll.title %>
</p>
<p>
	<strong>Description:</strong>
	<%= @poll.description %>
</p>
<p>
	<strong>Votes:</strong>
	<%= @poll.votes %>
</p>
<p>
	<div id="4b" style="padding-left: 5px; padding-right: 5px; padding-top: 5px; padding-bottom: 5px; margin-left:4em">
		<strong>Questions:</strong>
		<ul>
			<% @questions.each do |question|  %>
			<li>
				<%= question.description %>
			</li>
			<% end %>
		</ul>
	</div>
	<%= link_to 'Edit', edit_poll_path(@poll) %> |
	<%= link_to 'Back', polls_path %>